# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'TV Remote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV Remote
  pod 'Alamofire'


end
